files:
  index: resources/views/components/ui/slider/index.blade.php
  slider-js: resources/js/components/slider.js
  slider-css: resources/css/components/slider.css
dependencies:
  external: [
    noUiSlider: 'npm install nouislider'
  ]  